---
  - name: APT | Update apt
    apt: update_cache=yes
  - apt: name={{ item }} state=latest
    with_items:
      - bc
      - git
      - zip
      - unzip
      - python-pip
      - docker.io
  - apt: upgrade=dist
