---
  - pip: name=docker-py
  - name: consul server
    docker:
      name: consul
      image: progrium/consul
      state: started
      ports:
        - 8300:8300
        - 8302:8302
        - 8400:8400
        - 8500:8500
        - 8600:8600
      volumes:
        - /data
      command: "-server -node {{ ansible_hostname }} -advertise {{ ansible_default_ipv4.address }} -advertise-wan {{ ansible_env.AWS_PUBLIC_IP }} -dc 'falconwiz-aws-us-east' -bootstrap -ui-dir /ui"
