---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - apt: update_cache=yes
    - name: NGINX | Install nginx
      apt: name=nginx state=latest
    - name: NGINX | Start nginx service
      service: name=nginx state=started
