---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - apt: update_cache=yes
    - name: NGINX | Install nginx
      apt: name=nginx state=latest
    - name: Copy files from local to remote machine
      unarchive: src=../master.tar.gz dest=/usr/share/nginx/html copy=yes owner=root group=www-data mode=0755
    - name: NGINX | Start nginx service
      service: name=nginx state=restarted
